"""Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

import math

def is_triangular(x):
    """a = 1, b = 1, c = -2x
    x is triangular if -1 + sqrt(1 + 8 * x) is an integer"""
    y = -1 + math.sqrt(1 + 8 * x)
    return y == int(y)

def is_pentagonal(x):
    """a = 3, b = -1, c = -2x
    x is pentagonal if (1 + sqrt(1 + 24 * x)) / 6 is an integer"""
    y = (1 + math.sqrt(1 + 24 * x)) / 6
    return y == int(y)

def is_hexagonal(x):
    """a = 2, b = -1, c = -x
    x is hexagonal if (1 + sqrt(1 + 8 * x)) / 4 is an integer
    """
    y = (1 + math.sqrt(1 + 8 * x)) / 4
    return y == int(y)

n = 285
while True:
    n += 1
    candidate = n * (n + 1) / 2
    if is_pentagonal(candidate) and is_hexagonal(candidate):
        break
print n
print '%s is the next triangular number' % candidate